---
title: "Characterizing and Displaying Multivariate Data"
date: "7/02/2021"
output:
  html_document: default
---

# Bivariate Random Variables


```{r}
library(ggplot2)
library(dplyr)
library(readxl)
library(here)

theme_set(theme_minimal())
```

```{r}
table_3_1 <- readr::read_fwf(here('ma_book_data', 'T3_1_HEIGHTWT.DAT'))                        
colnames(table_3_1) <- c('person', 'height', 'weight')
table_3_1 %>% rmarkdown::paged_table()
```

```{r}
ggplot(table_3_1, aes(x = height, y = weight)) +
  geom_point() +
  geom_vline(linetype = "longdash", xintercept = mean(table_3_1$height)) + 
  geom_hline(linetype = "longdash", yintercept = mean(table_3_1$weight))
```

## Covariance

```{r}
with(table_3_1, cov(height, weight))
```

```{r}
(x_bar <- mean(table_3_1$height))
(y_bar <- mean(table_3_1$weight))

(with(table_3_1, sum(height * weight)) - nrow(table_3_1)* x_bar * y_bar)/(nrow(table_3_1) - 1)
```

```{r}
(b_1 <- coef(lm(height ~ weight, data = table_3_1))['weight'])

with(table_3_1, cov(height, weight)/var(weight))
```

## Correlation

```{r}
with(table_3_1, cov(height, weight)/(sd(height) * sd(weight)))

with(table_3_1, cor(height, weight))
```


# Visualization

```{r}
table_3_2 <- readr::read_fwf(here('ma_book_data/T3_2_VOTE.DAT'))
mat_3_2 <- as.matrix(table_3_2[, -1])


rownames(mat_3_2) <- table_3_2$X1
colnames(mat_3_2) <- as.character(c(32, 36, 40, 60, 64, 68))
stars(mat_3_2, key.loc = c(-1, 6), frame.plot =  T, full = T)
```



```{r}
table_3_3 <- readr::read_delim(here('ma_book_data','T3_3_BAKER.DAT'), delim = "  ",
                               col_names = c("x", "y", "corn97bu", "b", "ca", "cu", "fe", "k",
                                             "mg", "mn", "na", "p", "zn"))
```

```{r}
pairs(~ca + fe + corn97bu, data = table_3_3)
pairs(~ca + log(fe) + log(corn97bu), data = table_3_3)
```

```{r fig.height=10, fig.width=10}
pairs(table_3_3[,-(1:2)], pch = ".'")
```

# Linear Combinations

```{r}
table_3_6 <- readr::read_fwf(here::here('ma_book_data/T3_6_PROBE.DAT'))
colnames(table_3_6) <- c("subject", "y1", "y2", "y3", "y4", "y5")
table_3_6

y <- as.matrix(table_3_6[,-1])
```

```{r}
A <- matrix(c(1,1,1,1,1,
              2, -3, 1, -2, -1,
              -1, -2, 1, -2, 3
              ), ncol = 5, byrow = T)

A
```

```{r}
Z <- A %*% t(y)
Z

# bar_z
(Z %*% matrix(1, nrow = ncol(Z), ncol = 1))/nrow(y)
```


# Other tools/thoughts

## Careful with linear correlations

```{r}
set.seed(12345)

x <- exp(rnorm(1000))
y <- 1/x

plot(x, y)

cor(x, y, method = "pearson") # default method

cor(x,y, method = "spearman")

cor(rank(x), rank(y), method = "pearson")

```



## Simulating Random Multivariate Data

```{r}
set.seed(84)
mat_3_3 <- as.matrix(table_3_3[, -c(1:2)])

new_data <- mvtnorm::rmvnorm(1000, colMeans(mat_3_3), sigma = cov(mat_3_3))


head(new_data)



qqplot(mat_3_3[,"b"], new_data[, "b"])
lines(c(0,100), y = c(0, 100))


qqplot(mat_3_3[,"ca"], new_data[, "ca"])
lines(c(0,1e6), y = c(0, 1e6))
```

