---
title: "Clustering"
date: "11/11/2021"
output:
  html_document: default
---


```{r}
library(here)
library(ggplot2)
library(dplyr)

table15_1 <- readr::read_table(here('ma_book_data', 'T15_1_CITYCRIME.dat'),
                             col_names = c("city", "murder", "rape", 
                                           "robbery", "assault", "burglary", "arceny", "autotheft"))

mat_15_1 <- as.matrix(table15_1[, -1])
rownames(mat_15_1) <- table15_1$city
```



```{r}
dim(mat_15_1)
mat_15_1
```

```{r}
dist_mat_15_1 <- dist(mat_15_1, method = "euclidean")
```

```{r}
single_link <- hclust(dist_mat_15_1, method = "single")
```

```{r}
single_link
```


```{r}
plot(single_link)
```

```{r}
plot(as.dendrogram(single_link))
```



```{r}
hclust_method <- c("single", "complete", "average", "centroid", "median", "ward.D")
names(hclust_method) <- hclust_method

all_clust <- purrr::map(hclust_method, ~hclust(d = dist_mat_15_1, method = .x))

```

```{r, out.width = '50%', fig.show='hold'}
purrr::walk(all_clust, plot)
```


## Non-Hierarchical Methods

```{r}
table15_7 <- readr::read_table(here('ma_book_data', 'T15_7_PROTEIN.dat'),
                               col_names = c("country", "redmeat", "whitemeat", 
                                           "eggs", "milk", "fish", "cereals", "starchy", "nuts", "fruitveg")
                               
                               )

table15_7
mat15_7 <- as.matrix(table15_7[,-1])
rownames(mat15_7) <- table15_7$country


mat15_7
scaled_mat15_7 <- scale(mat15_7)
```


### Forgy Algorithm

```{r}
# note I had to run this a few times to make sure
set.seed(2398)
random_start <- kmeans(scaled_mat15_7, centers = 5, algorithm = "Forgy")
```

```{r}

lda_random <- MASS::lda(scaled_mat15_7 ,random_start$cluster )

as_tibble(predict(lda_random)$x) %>% 
  mutate(cluster = random_start$cluster) %>% 
  ggplot(aes(x = LD1, y = LD2, label = cluster)) + 
  geom_text()

```


### Default Algorithm

```{r}
# this one was more consistent
set.seed(2398)
random_start <- kmeans(scaled_mat15_7, centers = 5, algorithm = "Hartigan-Wong")
```

```{r}

lda_random <- MASS::lda(scaled_mat15_7 ,random_start$cluster )

as_tibble(predict(lda_random)$x) %>% 
  mutate(cluster = random_start$cluster) %>% 
  ggplot(aes(x = LD1, y = LD2, label = cluster)) + 
  geom_text()

```


### Centroids from average cluster

```{r}
(hclust_clusters <- hclust(dist(scaled_mat15_7), method = "average") %>% 
  cutree(k = 5))


(hclust_means <- split(as.data.frame(scaled_mat15_7), hclust_clusters) %>% 
  purrr::map(colMeans) %>% 
  purrr::reduce(rbind))


centroid_start <- kmeans(scaled_mat15_7, centers = hclust_means)
```

```{r}
# the LDA is not the same as in the book - I'm not sure why that is but the algorithm may be different
lda_centroid <- MASS::lda(scaled_mat15_7 ,centroid_start$cluster )

as_tibble(predict(lda_centroid)$x) %>% 
  mutate(cluster = centroid_start$cluster) %>% 
  ggplot(aes(x = LD1, y = LD2, label = cluster)) + 
  geom_text()


centroid_start
```

```{r}
dist_from_cent <- centroid_start$cluster %>% 
  purrr::imap_dbl(function(clust, country) {
    
    clust_center <- centroid_start$centers[clust, ]
    sqrt(sum((scaled_mat15_7[country, ] - clust_center)^2))
  })

split( dist_from_cent, f = centroid_start$cluster) %>% 
  purrr::map(sort)

```


## Clustering Variables

```{r}

mat_15_1_transformed <- cbind(mat_15_1, "inv_burglary" = 1/(mat_15_1[,"burglary"]))

(1 - abs(cor(mat_15_1_transformed, method = "spearman"))) %>% 
  as.dist() %>% 
  hclust(method = "average") %>% 
  plot()


(1 - abs(cor(mat_15_1_transformed, method = "pearson"))) %>% 
  as.dist() %>% 
  hclust(method = "average") %>% 
  plot()
```

## Mixtures

```{r}
library(mclust)

mclust_obj <- Mclust(scale(mat15_7, center = F, scale = F), G = 5, modelNames = "EEE")
mclust_obj$parameters


predict(mclust_obj)


setNames(predict(mclust_obj)$classification, rownames(mat15_7)) %>% 
  sort()


```

