---
title: "Discriminant Analysis"
date: "12/02/2021"
output:
  html_document: default
editor_options: 
  chunk_output_type: inline
---


```{r}
library(here)
library(ggplot2)
library(dplyr)
```

# Discriminant Analysis

```{r}
steel <- readr::read_fwf(here('ma_book_data','T8_1_STEEL.DAT'))
colnames(steel) <- c('temp', 'yp', 'strength')

steel$temp <- as.factor(steel$temp)
steel
```

```{r}
steel %>% 
  ggplot(aes(x = yp, y = strength, color = temp)) +
  geom_point()

steel_mat <- as.matrix(steel[,-1])
rownames(steel_mat) <- steel$temp
```

```{r}
calc_t2_stat <- function(x, y) {
  calcs <- list(x, y) %>%
    purrr::map(function(i) {
      list(y = colMeans(i),
           S = cov(i),
           n = nrow(i))
    })
  
  
  S_pl <- 1 / (calcs[[1]]$n + calcs[[2]]$n - 2) *
    (((calcs[[1]]$n - 1) * calcs[[1]]$S) + ((calcs[[2]]$n - 1) * calcs[[2]]$S))
  
  T2 <-
    (calcs[[1]]$n * calcs[[2]]$n) / (calcs[[1]]$n + calcs[[2]]$n) *
    t(calcs[[1]]$y - calcs[[2]]$y) %*% solve(S_pl) %*% (calcs[[1]]$y - calcs[[2]]$y)
  
  list(S_pl = S_pl,
       # convert from matrix to atomic
       T2 = as.numeric(T2))
  
}


split_steel <- split(steel %>% select(-temp), steel$temp, drop = T) 

h_test <- Hotelling::hotelling.test(split_steel[[1]],
                                    split_steel[[2]])

pooled_var <- calc_t2_stat(split_steel[[1]], split_steel[[2]])$S_pl

(y1_bar <- colMeans(steel_mat[rownames(steel_mat) == 1, ]))
(y2_bar <- colMeans(steel_mat[rownames(steel_mat) == 2, ]))

(a <- solve(pooled_var) %*% (y1_bar - y2_bar))


(steel_mat %*% a)
```



```{r}
line_slope = -a[2,1]/a[1,1]
```

```{r}

point_pass_through <- colMeans(steel_mat)

y_inter <- point_pass_through["strength"] - point_pass_through["yp"]* line_slope

steel %>% 
  ggplot(aes(x = yp, y = strength, color = temp)) +
  geom_point() +
  geom_abline(intercept = y_inter, slope = line_slope)
```

```{r}
table_8_3 <- readr::read_fwf(here::here('ma_book_data', 'T8_3_FOOTBALL.DAT'))
colnames(table_8_3) <- c('group', 'wdim', 'circum', 'fbeye', 'eyehd', 'earhd', 'jaw')
```


```{r}
# same values as book besides negative sign
MASS::lda(group ~ ., data = table_8_3) 
```

## Standardize Coefficients

```{r}

calc_spl <- function(x) {
  calcs <- x %>%
    purrr::map(function(i) {
      list(y = colMeans(i),
           S = cov(i),
           n = nrow(i))
    })

  part1 <- 1/(sum(purrr::map_dbl(calcs, "n")) - length(calcs))
        
  part2 <- purrr::map(calcs, ~(.x$n - 1) * .x$S) %>% 
    purrr::reduce(`+`)
  
  part1 * part2
}


x <- split(table_8_3[, -1], table_8_3$group)


pooled_covar <- calc_spl(x)
  
lda_fit <- MASS::lda(group ~ ., data = table_8_3) 

(scaled_lda <- sqrt(diag(diag(pooled_covar))) %*% lda_fit$scaling)


rownames(scaled_lda) <- rownames(pooled_covar)

scaled_lda
order(abs(scaled_lda[, 1]), decreasing = T)
```

## Test for significance

```{r}
H <- purrr::map(x, function(h) {
  out <- matrix(colMeans(h) - colMeans(bind_rows(x)), ncol = 1)
  out %*% t(out)
}) 


H <- purrr::reduce(H, `+`) * nrow(bind_rows(x))/length(x)

E <- purrr::map(x, function(e) {
  out <- t(e) - colMeans(e)
  out %*% t(out)
}) %>% 
  purrr::reduce(`+`)


eigen_vals <- eigen(solve(E) %*% H)$values
first_two_eigens <- as.numeric(eigen_vals[1:2])


Lambda1 <- prod(1/(1+first_two_eigens))
Lambda2 <- prod(1/(1+first_two_eigens[-1]))

Lambda1
Lambda2
```

## Plotting

```{r}
preds_vals <- predict(lda_fit)
preds_vals

# negative plotted to match book
cbind(
  as_tibble(preds_vals$x),
  group = as.factor(table_8_3$group)
) %>%
  group_by(group) %>% 
  mutate(mean_LD1 = mean(-LD1), mean_LD2 = mean(-LD2)) %>% 
  ggplot(aes(x = -LD1, y = -LD2, color = group)) +
  geom_point(alpha = .8) +
  geom_point(aes(x = mean_LD1, y = mean_LD2), size = 6) +
  theme_minimal()



cbind(
  as_tibble(preds_vals$x),
  group = as.factor(table_8_3$group)
) %>% 
  ggplot(aes(x = -LD1, color = group))+ 
  geom_density()

cbind(
  as_tibble(preds_vals$x),
  group = as.factor(table_8_3$group)
) %>% 
  ggplot(aes(x = -LD2, color = group))+ 
  geom_density()

```

# Classification Analysis
