---
title: "Matrix Algebra"
date: "8/26/2021"
output:
  html_document: default
---

# Basic Matrix Algebra

## Defining Objects

### Matrices

```{r}
matrix(data = c(23, 3.54,
                29, 3.81,
                18, 2.75), 
       ncol = 2, byrow = TRUE)
```

It's important to specify `byrow = TRUE`, default is `FALSE`

```{r}
A <- matrix(data = c(23, 3.54,
                29, 3.81,
                18, 2.75), 
       ncol = 2, byrow = FALSE)

A
```

### Vectors

```{r}
x <- c(98, 86, 93, 97)

dim(x)

x
```


```{r}
x_mat <- matrix(data = c(98, 86, 93, 97), 
       ncol = 1)

dim(x_mat)

x_mat
```

## Basic manipulation

### Transpose

```{r}
A

t(A)

t(t(A))
```

```{r}
x
t(t(x))

x_mat
t(x_mat)
```

### Addition/Subtraction

```{r}
A <- matrix(c(-2, 3, 7, 5, 1, -6), ncol = 2)
A

B <- matrix(c(3, -2,
              4, 5,
              10, -3), byrow = TRUE, ncol = 2)
B

A + B

A - B

```

### Multiplication

```{r}
A <- matrix(c(2, 4, 5, 1, 1, 6, 2, 3, 3, 5, 3, 2),
            ncol = 3)
B <- matrix(c(1, 2, 3, 4, 6, 8), ncol = 2)
            

A %*% B
```

```{r}
try(A * B)
```

```{r}
try(B %*% A)
```

```{r}
dim(A)
dim(B)

dim(A %*% B)
```

```{r}
length(A)

A
```

# Additional Properties and Operations

## Rank

```{r}
A
Matrix::rankMatrix(A)
```

## Inverse

```{r}
(A <- matrix(c(3, 2, 4, 6), ncol = 2))

Matrix::rankMatrix(A)

(A_inv <- solve(A))

solve(A_inv)

A %*% A_inv
```

## Positive Definite

```{r}
A <- matrix(c(3, 0, -3,
              0, 6, 3,
              -3, 3, 6), byrow = T, ncol = 3)

A
chol(A)
matrix(c(sqrt(3), 0, -sqrt(3),
              0, sqrt(6), sqrt(1.5),
              0, 0, sqrt(1.5)), byrow = T, ncol = 3)
```

## Determinate

```{r}

A <- matrix(c(1, -3, 2, 5), nrow = 2)
B <- matrix(c(4, 1, 2, 3), nrow = 2)

det(A)
det(B)

det(A %*% B)
det(B %*% A)
det(A) * det(B)
```

```{r}
det(A)


det(solve(A))
1/det(A)
```

```{r}
A <- matrix(c(5, 2, 3, 4, -3, 7, 4, 1, 9),
            ncol = 3
            
            )


sum(diag(A))
```


## Eigenvalues and Eigenvectors

```{r}
A <- matrix(c(1, -1, 2, 4), ncol = 2)

eigen(A)
matrix(c(1, -1, 2, 4), ncol = 2)
```

